from datetime import datetime, timezone

from flask_login import UserMixin

from extensions import db


def _utcnow():
    return datetime.now(timezone.utc)


class User(UserMixin, db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True, nullable=False, index=True)
    username = db.Column(db.String(80), unique=True, nullable=False, index=True)
    password_hash = db.Column(db.String(255), nullable=False)
    # Fernet-encrypted Anthropic API key supplied by the user at registration
    llm_api_key_encrypted = db.Column(db.Text, nullable=True)
    created_at = db.Column(
        db.DateTime(timezone=True), default=_utcnow, nullable=False
    )

    profile_entries = db.relationship(
        "UserProfile",
        back_populates="user",
        cascade="all, delete-orphan",
        order_by="UserProfile.created_at",
    )
    readings = db.relationship(
        "Reading",
        back_populates="user",
        cascade="all, delete-orphan",
        order_by="Reading.created_at.desc()",
    )

    def __repr__(self) -> str:
        return f"<User {self.username!r}>"


class UserProfile(db.Model):
    __tablename__ = "user_profiles"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(
        db.Integer, db.ForeignKey("users.id"), nullable=False, index=True
    )
    # Onboarding question shown to the user and their free-text answer
    question = db.Column(db.Text, nullable=False)
    answer = db.Column(db.Text, nullable=False)
    created_at = db.Column(
        db.DateTime(timezone=True), default=_utcnow, nullable=False
    )

    user = db.relationship("User", back_populates="profile_entries")

    def __repr__(self) -> str:
        return f"<UserProfile user_id={self.user_id!r}>"


class Reading(db.Model):
    __tablename__ = "readings"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(
        db.Integer, db.ForeignKey("users.id"), nullable=False, index=True
    )
    spread_type = db.Column(db.String(50), nullable=False)
    # Optional intention/question the user sets before drawing
    intention = db.Column(db.Text, nullable=True)
    # JSON array of card objects, each with keys:
    #   index, position_label, represents, card, orientation, interpretation
    cards_json = db.Column(db.JSON, nullable=False)
    # Final summary paragraph generated by the LLM
    narrative = db.Column(db.Text, nullable=True)
    created_at = db.Column(
        db.DateTime(timezone=True), default=_utcnow, nullable=False
    )

    user = db.relationship("User", back_populates="readings")

    def __repr__(self) -> str:
        return f"<Reading id={self.id!r} spread={self.spread_type!r}>"
